"""
API endpoints for evidence building and preview generation.
"""

from fastapi import APIRouter, UploadFile, File, Form, HTTPException, Request
from fastapi.responses import Response
from typing import List
from datetime import datetime
import io
from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas
from reportlab.lib.utils import ImageReader
from PIL import Image
import tempfile
import os
from app.services.entity_enrichment import EntityEnrichmentService

router = APIRouter()


@router.post("/generate-preview")
async def generate_preview(
    request: Request,
    textContent: str = Form(""),
    evidenceType: str = Form(...),
    standard: str = Form(...),
):
    """
    Generate a preview PDF combining uploaded images and text content.
    This creates a formatted evidence preview using AI-assisted layout.
    """
    try:
        print(f"Generating preview for: {evidenceType}, Standard: {standard}")
        print(f"Text content length: {len(textContent) if textContent else 0}")
        
        # Parse multipart form data to get images
        form = await request.form()
        images_list = []
        # FastAPI returns multiple files with same key as a list
        images_field = form.getlist("images")
        for item in images_field:
            if isinstance(item, UploadFile):
                images_list.append(item)
        
        print(f"Number of images: {len(images_list)}")
        # Create PDF buffer
        buffer = io.BytesIO()
        c = canvas.Canvas(buffer, pagesize=letter)
        width, height = letter

        # Page 1: Cover/Title
        c.setFont("Helvetica-Bold", 20)
        c.drawString(50, height - 100, evidenceType)
        c.setFont("Helvetica", 12)
        c.drawString(50, height - 130, f"Standard: {standard}")
        c.drawString(50, height - 150, "Evidence Preview - Generated by AI")

        # Page 2+: Content
        y_position = height - 100

        # Enrich text with entity background information
        # Use original text by default, only enrich if quick
        enriched_content = textContent
        if textContent.strip():
            try:
                # Try to enrich, but don't block if it takes too long
                enrichment_result = EntityEnrichmentService.enrich_text(textContent)
                enriched_content = enrichment_result["enriched_text"]
            except Exception as e:
                print(f"Error enriching text (using original): {e}")
                # Always fallback to original text if enrichment fails
                enriched_content = textContent

        # Add text content if provided
        if enriched_content and enriched_content.strip():
            # Add original evidence description
            c.setFont("Helvetica-Bold", 14)
            c.drawString(50, y_position, "Evidence Description:")
            y_position -= 30

            c.setFont("Helvetica", 11)
            # Extract original text (before enrichment section)
            original_text = enriched_content.split("--- Contextual Background Information ---")[0].strip()
            
            # Simple text wrapping for original text
            words = original_text.split()
            line = ""
            for word in words:
                if c.stringWidth(line + word, "Helvetica", 11) < width - 100:
                    line += word + " "
                else:
                    if line:
                        c.drawString(50, y_position, line.strip())
                        y_position -= 15
                    line = word + " "
                    if y_position < 50:
                        c.showPage()
                        y_position = height - 50
            if line:
                c.drawString(50, y_position, line.strip())
                y_position -= 30

            # Add background information section if available
            if "--- Contextual Background Information ---" in enriched_content:
                y_position -= 20
                if y_position < 100:
                    c.showPage()
                    y_position = height - 50
                
                c.setFont("Helvetica-Bold", 12)
                c.drawString(50, y_position, "Contextual Background Information:")
                y_position -= 25
                
                c.setFont("Helvetica", 10)
                # Extract and add background sections
                background_section = enriched_content.split("--- Contextual Background Information ---")[1]
                background_paragraphs = background_section.split("[Background:")
                
                for para in background_paragraphs:
                    if para.strip():
                        # Format: Entity Name] Background text
                        if "]" in para:
                            entity_part, bg_text = para.split("]", 1)
                            entity_name = entity_part.strip()
                            bg_text = bg_text.strip()
                            
                            # Add entity name in bold
                            c.setFont("Helvetica-Bold", 10)
                            c.drawString(50, y_position, f"{entity_name}:")
                            y_position -= 15
                            
                            # Add background text
                            c.setFont("Helvetica", 9)
                            words = bg_text.split()
                            line = ""
                            for word in words:
                                if c.stringWidth(line + word, "Helvetica", 9) < width - 100:
                                    line += word + " "
                                else:
                                    if line:
                                        c.drawString(60, y_position, line.strip())
                                        y_position -= 12
                                    line = word + " "
                                    if y_position < 50:
                                        c.showPage()
                                        y_position = height - 50
                            if line:
                                c.drawString(60, y_position, line.strip())
                                y_position -= 20
                
                y_position -= 20
        elif not images_list:
            # If no text and no images, add a message
            c.setFont("Helvetica", 11)
            c.drawString(50, y_position, "No content provided. Please add text or images.")

        # Add images
        for idx, image_file in enumerate(images_list):
            if y_position < 200:
                c.showPage()
                y_position = height - 50

            try:
                # Read image
                image_data = await image_file.read()
                img = Image.open(io.BytesIO(image_data))

                # Resize if too large
                max_width = width - 100
                max_height = 300
                img.thumbnail((max_width, max_height), Image.Resampling.LANCZOS)

                # Save to temp file for reportlab
                with tempfile.NamedTemporaryFile(delete=False, suffix=".png") as tmp:
                    img.save(tmp.name, "PNG")
                    tmp_path = tmp.name

                # Add image to PDF
                c.drawImage(tmp_path, 50, y_position - img.height, width=img.width, height=img.height)
                y_position -= img.height + 20

                # Clean up temp file
                os.unlink(tmp_path)

                # Add caption
                c.setFont("Helvetica", 9)
                c.drawString(50, y_position, f"Image {idx + 1}: {image_file.filename}")
                y_position -= 20

            except Exception as e:
                print(f"Error processing image {image_file.filename}: {e}")
                continue

        # Ensure we have at least one page
        if not images_list and not (enriched_content and enriched_content.strip()):
            c.setFont("Helvetica", 11)
            c.drawString(50, height - 100, "No content provided.")

        c.save()
        buffer.seek(0)
        
        print(f"PDF generated successfully, size: {len(buffer.getvalue())} bytes")

        return Response(
            content=buffer.getvalue(),
            media_type="application/pdf",
            headers={"Content-Disposition": f'inline; filename="evidence-preview.pdf"'},
        )

    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Error generating preview: {str(e)}")


@router.post("/save")
async def save_evidence(
    request: Request,
    evidenceType: str = Form(...),
    standard: str = Form(...),
    textContent: str = Form(""),
    applicationId: str = Form("demo-app"),  # For now using demo, later from auth
):
    """
    Save evidence to database and storage.
    For MVP, we'll store in memory. Later integrate with database and S3.
    Validates evidence quota: MC must have 4, each OC must have 3.
    """
    try:
        # Check current evidence counts
        if not hasattr(save_evidence, "evidence_store"):
            save_evidence.evidence_store = {}
        
        existing_evidences = [
            ev for ev in save_evidence.evidence_store.values()
            if ev.get("applicationId") == applicationId
        ]
        
        current_counts = {
            "MC": len([e for e in existing_evidences if e.get("standard") == "MC"]),
            "OC1": len([e for e in existing_evidences if e.get("standard") == "OC1"]),
            "OC2": len([e for e in existing_evidences if e.get("standard") == "OC2"]),
            "OC3": len([e for e in existing_evidences if e.get("standard") == "OC3"]),
        }
        
        # Validate quota before saving
        if standard == "MC" and current_counts["MC"] >= 4:
            raise HTTPException(
                status_code=400, 
                detail=f"Cannot save: MC already has 4 evidence files (maximum required). Current: {current_counts['MC']}/4"
            )
        elif standard in ["OC1", "OC2", "OC3"] and current_counts[standard] >= 3:
            raise HTTPException(
                status_code=400, 
                detail=f"Cannot save: {standard} already has 3 evidence files (maximum required). Current: {current_counts[standard]}/3"
            )
        # Parse images from form
        form = await request.form()
        images_list = []
        images_field = form.getlist("images")
        for item in images_field:
            if isinstance(item, UploadFile):
                images_list.append(item)
        
        # Generate evidence ID
        import uuid
        evidence_id = str(uuid.uuid4())
        
        # For MVP: Store in memory (later move to database)
        # In production: Save images to S3, store metadata in database
        evidence_data = {
            "id": evidence_id,
            "evidenceType": evidenceType,
            "standard": standard,
            "textContent": textContent,
            "imageCount": len(images_list),
            "imageNames": [img.filename for img in images_list],
            "applicationId": applicationId,
            "createdAt": datetime.utcnow().isoformat(),
            "status": "Draft",
        }
        
        # Store in global dict for MVP (in production, use database)
        if not hasattr(save_evidence, "evidence_store"):
            save_evidence.evidence_store = {}
        save_evidence.evidence_store[evidence_id] = evidence_data
        
        return {
            "message": "Evidence saved successfully",
            "evidence_id": evidence_id,
            "evidence": evidence_data
        }
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Error saving evidence: {str(e)}")


@router.get("/list")
async def list_evidence(applicationId: str = "demo-app"):
    """
    List all saved evidence for an application.
    """
    if not hasattr(save_evidence, "evidence_store"):
        save_evidence.evidence_store = {}
    
    evidence_list = [
        ev for ev in save_evidence.evidence_store.values()
        if ev.get("applicationId") == applicationId
    ]
    
    return {"evidence": evidence_list}


@router.get("/{evidence_id}")
async def get_evidence(evidence_id: str):
    """
    Get a specific evidence by ID.
    """
    if not hasattr(save_evidence, "evidence_store"):
        save_evidence.evidence_store = {}
    
    evidence = save_evidence.evidence_store.get(evidence_id)
    if not evidence:
        raise HTTPException(status_code=404, detail="Evidence not found")
    
    return {"evidence": evidence}


@router.delete("/{evidence_id}")
async def delete_evidence(evidence_id: str):
    """
    Delete an evidence.
    """
    if not hasattr(save_evidence, "evidence_store"):
        save_evidence.evidence_store = {}
    
    if evidence_id not in save_evidence.evidence_store:
        raise HTTPException(status_code=404, detail="Evidence not found")
    
    del save_evidence.evidence_store[evidence_id]
    return {"message": "Evidence deleted successfully"}

